### ISSUE TITLE
Update routes formatter to use Parlour

### ISSUE THREAD

**Issue by connorshea** [chanzuckerberg/sorbet-rails#102]
The routes formatter should be updated like the model formatter to use Parlour, for consistency :)

**Comment by connorshea** [comment]
I tried doing this, and boy that is a lot more complex than I anticipated. Right now, it uses a `RouteInspector` that's technically supposed to be a private API, and it abuses some formatting tricks to output an RBI. I couldn't find a good (public API) way to consistently, programatically get all the routes available in a Rails app, unfortunately. :/

**Comment by manhhung741** [comment]
I don't think you need to find a different way to get routes. The route inspector will call the formatter for each route that it has. The `RouteRbiFormatter` can assume the methods are called correctly. Essentially @buffer can be replaced with a `Parlour::RbiGenerator` and every time a `section` is called, we insert new methods to the generator. When `result` is called, outout the generated rbi.

This is the code in rails source code that I modeled after
https://github.com/rails/rails/blob/0196551e6039ca864d1eee1e01819fcae12c1dc9/actionpack/lib/action_dispatch/routing/inspector.rb#L234
