### ISSUE TITLE
New "Can't find gem for", "srb tc" errors, and todo.rbi line

### ISSUE THREAD

**Issue by jasnow** [chanzuckerberg/sorbet-rails#115]
**Describe the bug:**

7 new "srb tc" errors with latest sorbet-rails version

**Steps to reproduce:**

Try this after upgrading to edge (master version of) sorbet-rails gem.

1. Run sorbet "bundle install" with sorbet-rails pointing to a
    local updated copy of sorbet-rails
2. Run "srb init" then "rake rails_rbi:routes" then "rake rbi:models" then "srb tc".
3. Results:
 * Lots of new "Can't find gem for" messages.
 * This is new in sorbet/rbi/todo.rbi file: **module T::InterfaceWrapper::Helpers; end**
 * I got 8 "srb tc" errors - all Wizard or Wand related. Previously it was 0 errors. One example:
```
sorbet/rbi/hidden-definitions/hidden.rbi:19042: Method `Wizard.Slytherin` redefined without matching argument count. Expected: `0`, got: `1` https://srb.help/4010
       19042 |  def self.Slytherin(*args); end
                ^^^^^^^^^^^^^^^^^^^^^^^^^
    sorbet/rails-rbi/models/wizard.rbi:161: Previous definition
     161 |  def self.Slytherin; end
            ^^^^^^^^^^^^^^^^^^
```
**Expected behavior:**

Expect "srb tc" to produce 0 errors.
No "Can't find gem for" messages.
No new todo.rbi line.

**Versions:**
- Ruby: ruby 2.4.6p354 (2019-04-01 revision 67394) [x86_64-darwin16]
- Rails: Rails 5.2.3
- Sorbet: 0.4.4602
- Sorbet-Rails: 0.4.0 using "path: '../sorbet-rails' to use edge version.

**Comment by manhhung741** [comment]
You should rerun

```bundle exec srb rbi hidden-definition```

It is a new requirement I have documented in a new PR. Similarly, sorbet
also expect the same script be run when upgrading.

**Comment by jasnow** [comment]
Your previous comment fixed the "srb tc" issues. Will close this issue before getting answer to other 2 items. Will watch for them again when I get this thru rubygems.org.

**Comment by manhhung741** [comment]
The new todo is probably fine. Looks like it’s coming from Sorbet itself
:-?? Or maybe I have to extend T::Helpers hmm

Whats the cant find gem for messages?

**Comment by jasnow** [comment]
@manhhung741 
```
Can't find gem for /Users/macbookpro/Projects/sorbet-rails/lib/sorbet-rails/custom_finder_methods.rb
Can't find gem for /Users/macbookpro/Projects/sorbet-rails/lib/sorbet-rails/railtie.rb
Can't find gem for /Users/macbookpro/Projects/sorbet-rails/lib/sorbet-rails/model_utils.rb
Can't find gem for /Users/macbookpro/Projects/sorbet-rails/lib/sorbet-rails/model_plugins/base.rb
Can't find gem for /Users/macbookpro/Projects/sorbet-rails/lib/sorbet-rails/model_plugins/active_record_enum.rb
Can't find gem for /Users/macbookpro/Projects/sorbet-rails/lib/sorbet-rails/model_plugins/active_record_querying.rb
Can't find gem for /Users/macbookpro/Projects/sorbet-rails/lib/sorbet-rails/model_plugins/active_relation_where_not.rb
Can't find gem for /Users/macbookpro/Projects/sorbet-rails/lib/sorbet-rails/model_plugins/active_record_named_scope.rb
Can't find gem for /Users/macbookpro/Projects/sorbet-rails/lib/sorbet-rails/model_plugins/active_record_attribute.rb
Can't find gem for /Users/macbookpro/Projects/sorbet-rails/lib/sorbet-rails/model_plugins/active_record_assoc.rb
Can't find gem for /Users/macbookpro/Projects/sorbet-rails/lib/sorbet-rails/model_plugins/active_record_finder_methods.rb
Can't find gem for /Users/macbookpro/Projects/sorbet-rails/lib/sorbet-rails/model_plugins/custom_finder_methods.rb
Can't find gem for /Users/macbookpro/Projects/sorbet-rails/lib/sorbet-rails/model_plugins/enumerable_collections.rb
Can't find gem for /Users/macbookpro/Projects/sorbet-rails/lib/sorbet-rails/model_plugins/plugins.rb
Can't find gem for /Users/macbookpro/Projects/sorbet-rails/lib/sorbet-rails/model_rbi_formatter.rb
Can't find gem for /Users/macbookpro/Projects/sorbet-rails/lib/sorbet-rails.rb
```

**Comment by jasnow** [comment]
@manhhung741  - The above "Can't find gem for" is probably connected with the fact that I am using a special path for sorbet-rails gem.

**Comment by jasnow** [comment]
FYI: So I said - try this:"rake rails_rbi:helpers" and got:
rake aborted!
NoMethodError: undefined method `length' for nil:NilClass
