### ISSUE TITLE
Getting NoMethodError when your run "rake rails_rbi:helpers" command.

### ISSUE THREAD

**Issue by jasnow** [chanzuckerberg/sorbet-rails#120]
**Describe the bug:**

Getting **NoMethodError: undefined method `length' for nil:NilClass**
 when your run "rake rails_rbi:helpers" command.

**Steps to reproduce:**

 1. Clone my https://github.com/jasnow/rails_app5_2 repo.
 2. Run "rake rails_rbi:helpers" and you get:
```
rake aborted!
NoMethodError: undefined method `length' for nil:NilClass
/Users/USER/.rvm/gems/ruby-2.4.6@ruby2.4-rails5.2/gems/sorbet-rails-0.5.0/lib/sorbet-rails/tasks/rails_rbi.rake:53:in `block (2 levels) in <top (required)>'
/Users/USER/.rvm/gems/ruby-2.4.6@ruby2.4-rails5.2/gems/rake-12.3.3/exe/rake:27:in `<top (required)>'
/Users/USER/.rvm/gems/ruby-2.4.6@ruby2.4-rails5.2/bin/ruby_executable_hooks:24:in `eval'
/Users/USER/.rvm/gems/ruby-2.4.6@ruby2.4-rails5.2/bin/ruby_executable_hooks:24:in `<main>'
Tasks: TOP => rails_rbi:helpers
(See full trace by running task with --trace)
```
**Expected behavior:**

-- Generate sigs for helpers --

**Versions:**

- Ruby: ruby 2.4.6p354 (2019-04-01 revision 67394) [x86_64-darwin16]
- Rails: 5.2.3
- Sorbet: 0.4.4602
- Sorbet-Rails: 0.5.0

**Comment by manhhung741** [comment]
@connorshea do you know what can be wrong here? Maybe because there is no Helper?

**Comment by connorshea** [comment]
oh, hm yeah that'll do it.

We could probably fix it by changing this line to use `helpers&.length == 0 || helpers.nil?` or `helpers.nil? || helpers.length == 0`, though that might just cause an error to occur further along in the code instead.

https://github.com/chanzuckerberg/sorbet-rails/blob/6c600c0256084e76694475a3f3fdfc5c9e1b5dbe/lib/sorbet-rails/tasks/rails_rbi.rake#L53

**Comment by manhhung741** [comment]
We should do nothing if there is no helpers.

**Comment by connorshea** [comment]
That's specifically checking if the previous attempt to get the helpers returned anything, so it's supposed to check that there aren't any.

**Comment by manhhung741** [comment]
Ah the check on L53 is inverted. It should check helpers.nil? first then
check the length.

I think after that, and before we call the generator, we should check again
that helpers is defined before proceeding.
