### ISSUE TITLE
Unexpected modified files after running "run_all_specs.sh" today

### ISSUE THREAD

**Issue by jasnow** [chanzuckerberg/sorbet-rails#127]
**Describe the bug:**

Unexpected modified files after running "run_all_specs.sh" today

**Steps to reproduce:**

After upgrading sorbet-rails repos (488 files) this morning, I ran "./spec/bin/run_all_specs.sh" and it resulted in 35 modified files (new "typed:" lins I think) in sorbet-rails/spec/support/v5.2-no-sorbet. Confirmed connection with PR#117 and #126 .

**Expected behavior:**

No modified files after upgrading to latest sorbet-rails repo.

**Versions:**
- Ruby: ruby 2.4.6p354 (2019-04-01 revision 67394) [x86_64-darwin16]
- Rails: 5.2.3
- Sorbet: 0.4.4602
- Sorbet-Rails: 0.5.0

**Comment by jasnow** [comment]
@connorshea - I am thinking that I should add this text as a comment to #126 since that PR has not been merged. What do you think?

**Comment by connorshea** [comment]
I don’t think there’s a good way around this, so we should probably just run the script and commit the files with type sigils

**Comment by manhhung741** [comment]
Agree. I’m not bothered that the files have sigils. Lets just commit them.

**Comment by connorshea** [comment]
Fixed by #123

**Comment by jasnow** [comment]
Verified fixed so I'm closing this issue.
