### ISSUE TITLE
5 failed specs after upgrading sorbet-rails

### ISSUE THREAD

**Issue by jasnow** [chanzuckerberg/sorbet-rails#139]
**Describe the bug:**

Failed specs after upgrading sorbet-rails

**Steps to reproduce:**

After updating my fork of sorbet-rails this morning and running "bundle update" and "rake", I get 5 failed specs.
```
Failed examples:

spec ./spec/rake_rails_rbi_models_spec.rb:10 # rake rails_rbi:models generates model files correctly
rspec ./spec/rake_rails_rbi_models_spec.rb:51 # rake rails_rbi:models generates more than 1 selected models correctly
rspec ./spec/sorbet_spec.rb:54 # sorbet returns expected sorbet tc result
rspec ./spec/sorbet_spec.rb:64 # sorbet passes sorbet dynamic checks
rspec ./spec/sorbet_spec.rb:71 # sorbet runs with srb tc --lsp
```
**Expected behavior:**

No failed specs.

**Versions:**
- Ruby: 2.5.5p157
- Rails: 5.2.3
- Sorbet: 0.4.4673
- Sorbet-Rails: 0.5.2

**Comment by manhhung741** [comment]
Can you also include the error logs of the failed example?

We run spec every day so likely a new change on sorbet break something?

**Comment by jasnow** [comment]
Can't reproducing these issues so closing. 

I do see 
```
-    sorbet-rails (0.5.1)
+    sorbet-rails (0.5.2)
```
for each spec/support/vn.m/Gemfile.lock file.

**Comment by manhhung741** [comment]
Thats one is fine :-)

**Comment by jasnow** [comment]
Suggest checking in the above Gemfile.lock file changes or add them to .gitignore.
