### ISSUE TITLE
Support for mailers

### ISSUE THREAD

**Issue by jaredbeck** [chanzuckerberg/sorbet-rails#143]
**Describe the bug:**

Rails mailer actions are defined as instance methods but called as class methods. Sorbet is aware of the former, but not the later.

**Is it silly that rails works this way?**

Probably.

**Steps to reproduce:**

```ruby
# typed: true
class UserMailer < ApplicationMailer
  def new_user_password(user)
    # ...
  end
end

# typed: true
class BatchPasswordGenerator
  # ..
  sig { params(user: ::User).void }
  def enqueue_new_user_password_email(user)
    ::UserMailer.
      new_user_password(user).
      deliver_later
  end
  # ..
end
```

Produces:

```
bin/srb t
redacted/batch_password_generator.rb:38: Method new_user_password does not exist on T.class_of(UserMailer) https://srb.help/7003
    38 |      ::UserMailer.
    39 |        new_user_password(redacted).
    app/mailers/user_mailer.rb:24: Did you mean: UserMailer#new_user_password?
    24 |  def new_user_password(redacted)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Errors: 1
```

**Expected behavior:**

`srb t` should not produce error.

**Versions:**

```
bin/rails -v
Rails 6.0.0
ruby -v
ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin18]
bundle | grep sorb
Using sorbet-runtime 0.4.4686
Using sorbet-static 0.4.4686 (universal-darwin-18)
Using sorbet 0.4.4686
Using sorbet-progress 0.2.3
Using sorbet-rails 0.5.2
```

**Comment by manhhung741** [comment]
It depends if we can reflect on the typed signature of the instance method.

I asked the sorbet team & got a tip to do reflection for sorbet signature.
It is kinda secret API & subject to change. But it might worth doing.

I can give it a try later, but expect some delay. If anyone interested on a
PR, I can forward the tip to you.

**Comment by manhhung741** [comment]
I put together an PR for mailer rbi generation 😅 💦 
https://github.com/chanzuckerberg/sorbet-rails/pull/151
