### ISSUE TITLE
Generate methods for ActiveStorage attachments

### ISSUE THREAD

**Issue by connorshea** [chanzuckerberg/sorbet-rails#148]
**Describe the bug:**

SorbetRails doesn't currently generate methods for ActiveStorage attachments. For example, in my Rails app users have avatars and games have covers, but neither of these are typed.

**Steps to reproduce:**

```ruby
class User < ApplicationRecord
  has_one_attached :avatar
end
```

```ruby
class Game < ApplicationRecord
  has_one_attached :cover
end
```

In `hidden.rbi` we have some methods like this:

```ruby
module User::GeneratedAssociationMethods
  def avatar(); end

  def avatar=(attachable); end
end
```

**Expected behavior:**

It should return either [`ActiveStorage::Attached::One`](https://api.rubyonrails.org/classes/ActiveStorage/Attached/One.html) or [`ActiveStorage::Attached::Many`](https://api.rubyonrails.org/classes/ActiveStorage/Attached/Many.html) depending on the definition in the model.

This is what I'd expect to see in `game.rbi`:

```ruby
module Game::GeneratedAttributeMethods
  extend T::Sig
  
  sig { returns(T.nilable(ActiveStorage::Attached::One)) }
  def cover; end

  sig { params(attachable: T.untyped).returns(T.untyped) }
  def cover=(attachable); end

  # or, if we had something defined like `has_many_attached :covers`
  sig { returns(T.nilable(ActiveStorage::Attached::Many)) }
  def covers; end

  sig { params(attachable: T.untyped).returns(T.untyped) }
  def covers=(*attachables); end
end
```

I'm not entirely sure what the setters take or return, unfortunately.

**Versions:**
- Ruby: 2.6.2
- Rails: 6.0.0
- Sorbet: 
- Sorbet-Rails: 0.5.3 (master)

**Comment by connorshea** [comment]
I think you can get attachment names for a model like this

```ruby
User.attachment_reflections.keys
# => ["avatar"]
```

You can also get the type of attachment (`has_one_attached` vs `has_many_attached`) like this:

```ruby
User.attachment_reflections.values.map { |x| x.class }
# }=> [ActiveStorage::Reflection::HasOneAttachedReflection]
```

**Comment by manhhung741** [comment]
Sounds like you’ve got it figured out. Would you mind opening a PR for a
plugin?
