### ISSUE TITLE
Select has incorrect return type when passed a block

### ISSUE THREAD

**Issue by riley-klingler** [chanzuckerberg/sorbet-rails#152]
**Describe the bug:**
[ApplicationRecord.select](https://apidock.com/rails/v5.2.3/ActiveRecord/QueryMethods/select) has two different modes: one that takes a block and returns an Array, and one that takes any number of fields and returns an `ActiveRecord::Relation`. The `sig` that `sorbet-rails` generates claims it can only return a `Relation`.

**Steps to reproduce:**
```
class User < ApplicationRecord
end
```
Generated `rbi` file:
```
  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(User::ActiveRecord_Relation) }
  def select(*args, &block); end
```
**Expected behavior:**
To be honest, I'm not quite sure. Making the return type of `select` be `T.any(User::ActiveRecord_Relation, T::Array[User])` is not great, because callers will always have to check which type is being returned, even though it can always be inferred from the argument type. But it might be the best we can do, since ruby doesn't support overloading.

**Versions:**

- Ruby: 2.6.2
- Rails: Rails 5.2.3
- Sorbet:  0.4.4651
- Sorbet-Rails: 0.5.0

**Comment by manhhung741** [comment]
Hi Riley, like you said, `sorbet` doesn't support having 2 sig for one method. The `.select` method that returns an array is a select performed on the materialized element of an active record.

You can do this for typechecking instead: `User.all.to_a.select` <- this will take a block and returns an Array

**Comment by riley-klingler** [comment]
Do you want to remove the block as a parameter then? Right now, the `sig` produced implies that you can pass in a block and return an `ActiveRecord_Relation`, which will not happen. It also implies you can pass both `args` and a block, which will [throw a runtime error](https://github.com/rails/rails/blob/bdfd47053108f3e7757f35a6d3eee511bf6e0cc5/activerecord/lib/active_record/relation/query_methods.rb#L256).

**Comment by manhhung741** [comment]
Ah darn. Would you like to send a PR to remove &block and add an item to
“Tips and Tricks” about how to use `select` correctly?

`*args, &block` is the standard param for a bunch of delegate and/or
flexible methods. There might be more methods we can remove &block.

**Comment by pje** [comment]
> Making the return type of select be T.any(User::ActiveRecord_Relation, T::Array[User]) is not great, because callers will always have to check which type is being returned, even though it can always be inferred from the argument type.

Yeah, this is a limitation of Sorbet. Unless they start supporting sig overloading (mutltiple `sig`s per `def` ), this is impossible to express using the type system.

I agree that returning `T.any(User::ActiveRecord_Relation, T::Array[User])` is a worse user experience. 

My workaround is adding `to_a` before any enumerable `select`s, i.e. replacing this:

```ruby
User.where(foo: 'bar').select(&:some_predicate)
```

...with this:

```ruby
User.where(foo: 'bar').to_a.select(&:some_predicate)
```

🤷‍♂

**Comment by ghiculescu** [comment]
If the `block` argument doesn't get removed, there's another issue there where args it yields are treated by sorbet as `NilClass`.

```ruby
  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(User::ActiveRecord_Relation) }
  def select(*args, &block); end

  foo.users.select {|u| T.reveal_type(u)} # Revealed type: NilClass
```

If the generated sig looked like this:

```ruby
  sig { params(args: T.untyped, block: T.proc.params(user: User).void).returns(User::ActiveRecord_Relation) }
  def select(*args, &block); end

  foo.users.select {|u| T.reveal_type(u)} # Revealed type: User
```

It would be handy. At the moment you have to either call `to_a` as @pje said, or use `T.must` inside the block.

**Comment by manhhung741** [comment]
I'll work on something to remove the `&block` argument & add documentation
to reduce the confusion.
It might not come immediately though -- if any of you want to start a PR,
please feel free to let me know
