### ISSUE TITLE
A lot more "typed: ignore" files are been generated with srb commands

### ISSUE THREAD

**Issue by jasnow** [chanzuckerberg/sorbet-rails#153]
**Describe the bug:**

Yesterday, I saw a lot more "typed: ignore" files for my repos after running srb commands.
I saw several of them went from 0 "typed: ignore"s to 30+. 
Sample repo: https://github.com/jasnow/rails_5.2_new .
Gist of "typed: ignore" files: https://gist.github.com/jasnow/b26be8a79da4ff230c68e31769ae5f69

**Steps to reproduce:**

To see "srb tc" errors, just change "ignore" to "false" and run "srb tc". Thanks.

**Expected behavior:**

Very few or zero "typed: ignore" files

**Versions:**

For the above sample repo:
- Ruby: 2.4.7
- Rails: 5.2.3
- Sorbet: 0.4.4709
- Sorbet-Rails: 0.5.3

Note that this also happened for Ruby 2.6 and Rails 6.0 repos.

**Comment by manhhung741** [comment]
Thanks for flagging. Does this problem occur when you don't run sorbet-rails?

**Comment by manhhung741** [comment]
> To see "srb tc" errors, just change "ignore" to "false" and run "srb tc". Thanks.
Can you also provide a paste when you change all the `ignore` files to `false` and run `srb tc`?

**Comment by jasnow** [comment]
> Thanks for flagging. Does this problem occur when you don't run sorbet-rails?

Using above repo:

With sorbet-rails:
   2 # typed: autogenerated
  12 # typed: false
  33 # typed: ignore
  38 # typed: strong
  11 # typed: true
  96 TOTAL

Without sorbet-rails:
   2 # typed: autogenerated
   5 # typed: false
   6 # typed: ignore
   9 # typed: strict
  47 # typed: strong
  19 # typed: true
  88 TOTAL

**Comment by jasnow** [comment]
> To see "srb tc" errors, just change "ignore" to "false" and run "srb tc". Thanks. Can you
> also provide a paste when you change all the `ignore` files to `false` and run `srb tc`?

https://gist.github.com/jasnow/6b0e0a63a70af660f9aaecdfdc63471e

**Comment by manhhung741** [comment]
It looks like an issue with `sorbet-typed` -- 6 rails files were ignored before `sorbet-rails` added.
I've found them really difficult to resolve manually. Instead, reinitializing srb will make them go away

1- delete sorbet/ folder
2- run `srb init` 

Please let me know if this resolve your issue.

**Comment by jasnow** [comment]
Where have we documented the problem of method definition in BOTH sorbet-typed and sorbet/rbi/gems ? This example covered "activemodel" methods.

**Comment by manhhung741** [comment]
Likely it should be in sorbet-typed repo.

**Comment by jasnow** [comment]
Added question to Slack/Sorbet/Discuss channel.

**Comment by jasnow** [comment]
Found a workaround. Removed 'srb rbi suggest-typed' from my daily script. 
Now "srb tc" down to 1 error so I will work that separately.
```
sorbet/rbi/todo.rbi:1x: `ActiveStorage::Attachment` was 
previously defined as a `class` https://srb.help/4012
    1x |module ActiveStorage::Attachment; end
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by jasnow** [comment]
I expect to close this issue after I move this to "sorbet" or 
"sorbet-typed" to deal with the duplicate method definitions.

**Comment by manhhung741** [comment]
For sorbet rails tests, we run `srb init` every time before running
`sorbet-rails`. That’s probably a better workflow for you.

**Comment by jasnow** [comment]
When you say "running sorbet-rails", you mean "rake rails_rbi:all"

**Comment by manhhung741** [comment]
Yep

**Comment by jasnow** [comment]
Now I can re-add "srb rbi suggest-typed" and moved all rails_rbi command to the end.
Still have one "srb tc" error in todo.rbi file.
