### ISSUE TITLE
Define 'new' method on model classes

### ISSUE THREAD

**Issue by connorshea** [chanzuckerberg/sorbet-rails#174]
**Describe the bug:**
ActiveRecord overrides the `new` method for all Model classes, e.g. `User.new`.

It's defined like this in `activerecord.rbi`:
```ruby
module ActiveRecord::Inheritance::ClassMethods
  def new(attributes = nil, &block); end
end
```

And then `User`, or any other model, inherits that method.

**Expected behavior:**

I could have an `app/controllers/users_controller.rb` file like this:

```ruby
class UsersController < ApplicationController
  def create
    @user = User.new({ username: 'connor' }) # @user is T.untyped because `new` is overridden.
    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, success: "#{@user.username} was successfully created." }
    end
  end
end
```

The method should be generated as part of Sorbet Rails so its return type can be dynamically set:

```ruby
class User
  sig { params(args: T.untyped, block: T.untyped).returns(User) }
  def self.new(*args, &block); end
end
```

Unfortunately it can't just be `self_type` because that doesn't return an instance of the caller :/

**Comment by connorshea** [comment]
Actually, since we know what parameters it takes can we use the correct method signature?

```ruby
class User
  sig { params(attributes: T.untyped, block: T.untyped).returns(User) }
  def self.new(attributes = nil, &block); end
end
```

**Comment by connorshea** [comment]
@manhhung741 IIRC, you mentioned at once point that the Sorbet team didn't want to add a special type that'd return an instance of a class (e.g. instead of `T.self_type` it'd be `T.instance_of_self_type`), did they say why?

**Comment by manhhung741** [comment]
That reminds me... Does `Model.create` work? Do we also need one for it?

**Comment by connorshea** [comment]
`create` is handled in sorbet-typed right now, but it just returns `T.untyped`.

**Comment by manhhung741** [comment]
They want to add it, but they are still working on it. It’s also one of
their most requested features currently.

**Comment by connorshea** [comment]
Where should I put the `create_method` for this? 🤔
