### ISSUE TITLE
Getting "expected \<some-error> but nothing was raised" during "rake" run

### ISSUE THREAD

**Issue by jasnow** [chanzuckerberg/sorbet-rails#181]
**Steps to Reproduce:**

 * Clone my forked repo: https://github.com/jasnow/sorbet-rails.git
 * Run "rake" and see the 6 failed tests.

**Describe the bug:**

1. Yesterday and today, when I run "rake", I get these 6 failed tests:
```
rspec ./spec/custom_params_methods_spec.rb:58
rspec ./spec/custom_params_methods_spec.rb:64
rspec ./spec/custom_params_methods_spec.rb:98
rspec ./spec/custom_params_methods_spec.rb:131
rspec ./spec/boolean_string_spec.rb:52
rspec ./spec/integer_string_spec.rb:39
```

 2. All 6 error messages are of this format:
```
     Failure/Error:
       expect {
         ta.assert('<string>')
       }.to raise_error(some-error)

       expected <some-error> but nothing was raised
```

 3. Here is the "rake" log gist: https://gist.github.com/jasnow/9fd8dcd8ba7b31eb37827c01921d059a

 4. Yesterday when I was trying to debug this, I ran all the
    "rake update_spec_v#_#" commands  and the
    spec/bin/update_test_data.sh script. Looking at my current
    fork on GitHub, I see updated gem and ruby versions in Gemfile
    and Gemfile.lock files and several "typed" changes.

 5. My local code is sync'ed with my fork on GitHub.

**Expected behavior:**

I expect all the test to pass as they do on TravisCI.

**6. Versions:**
     -- Ruby: 2.5.6p201 (2019-08-28 revision 67796) [x86_64-darwin16]
     -- Rails: 5.2.3
     -- Sorbet: 0.4.4761
     -- Sorbet-rails: 0.5.5.1
     -- OS: 10.12.6

**Comment by jasnow** [comment]
After cloned yours and my forks and running "diff -r" on both directories and filtering
out misc (coverage, logs, ...), I have narrowed it down to these files;
 * sorbet-rails/spec/support/v5.2/sorbet/rbi/gems/activesupport.rbi
 * sorbet-rails/spec/support/v5.2/sorbet/rbi/gems/mail.rbi
 * sorbet-rails/spec/support/v5.2/sorbet/rbi/gems/rspec-core.rbi
 * sorbet-rails/spec/support/v5.2/sorbet/rbi/hidden-definitions/hidden.rbi

Will cover mine version into /tmp (yours) version and see what happens.

**Comment by jasnow** [comment]
Unclear what exactly is causing this but can't isolated it so closing this ticket.

**Comment by manhhung741** [comment]
Sorry I didn't have time to look at this yet. Might be some issue with the classes I introduced. I'll double check later

**Comment by jasnow** [comment]
@manhhung741  - Data Point: This morning, I resynced with your repo; pushed changes up to my my clone; recloned my repo and now I have no errors

**Comment by jasnow** [comment]
Went back to old clone and changed .rvmrc gemset - Ran bundle/etc/rake - 0 failed tests. Think I have solved my problem/CLOSED.
