### ISSUE TITLE
Add pluck_to_struct to relation

### ISSUE THREAD

**Issue by manhhung741** [chanzuckerberg/sorbet-rails#193]
**Describe the bug:**
This will be a convenient thing for getting structured objects out of a relation.

**Expected behavior:**
Wizard.all.pluck_to_struct(TA[StructName].new, :attribute1, :attribute2) -> T::Array[StructName]

**Versions:**

- Ruby:
- Rails:
- Sorbet:
- Sorbet-Rails:

**Comment by giovannibonetti** [comment]
Is that a method generated by Rails, or are you using the [pluck_to_hash gem](https://github.com/girishso/pluck_to_hash#using-pluck_to_struct)?

**Comment by manhhung741** [comment]
I implemented pluck_to_tstruct method to pluck to T::Struct object. It uses
Rails’s own pluck method, but based on the idea/implementation of
pluck_to_hash gem but not using the gem directly.

The title of this PR isn’t correct now, as I name the method
pluck_to_tstruct after realizing pluck_to_hash gem provides a
pluck_to_struct method

Please check out the documentation for pluck_to_tstruct

https://github.com/chanzuckerberg/sorbet-rails/blob/master/README.md#pluck_to_tstruct-instead-of-pluck

**Comment by manhhung741** [comment]
Added `pluck_to_tstruct` in #197
