### ISSUE TITLE
5 bundled_rbi related "srb tc" errors in rails_app5_2 repo for gems/sorbet-rails.rbi file

### ISSUE THREAD

**Issue by jasnow** [chanzuckerberg/sorbet-rails#202]
**Describe the bug:**

5 bundled_rbi related "srb tc" errors in https://github.com/jasnow/rails_app5_2 repo for gems/sorbet-rails.rbi file

**Steps to reproduce:**

On October 9, when I changed typed from false to true for
sorbet/rbi/gems/sorbet-rails.rbi and ran "srb tc", I got 5 errors.
See gist below for details.
https://gist.github.com/jasnow/b99bc9f4e4ccc5c50b7f219b0767cc78

Today when I repeat it, I get 9 errors.
Ran "srb rbi hidden-definitions" and got it down to 6 errors.
Ran "srb init"/etc again and got it down to the above 5 errors.

All 5 errors appear to be related to the sorbet-rails/bundled_rbi files.
If I comment out the contents of these files, "srb tc" is clean.

**Expected behavior:**

No errors

**Versions:**

- Ruby: 2.4.9p362 (2019-10-02 revision 67824) [x86_64-darwin16]
- Rails: 5.2.3
- Sorbet: 0.4.4865
- Sorbet-Rails: 0.5.7

**Comment by jasnow** [comment]
If I run "rails rails_rbi:all" and "rails rails_rbi:custom" from my scripts today (as a workaround), I get this added to my hidden.rbi file.
```
module ITypeAssert
  Elem = ::T.let(nil, ::T.untyped)
end

class TA
  Elem = ::T.let(nil, ::T.untyped)
end
```

**Comment by manhhung741** [comment]
Seems like this is fixed by running `rails_rbi:custom`. `rails_rbi:all` rake task will be kept up-to-date to run all rake tasks needed, including any new rake tasks added or changed
