### ISSUE TITLE
ActiveRecord_Relation used in types is private

### ISSUE THREAD

**Issue by ilyakatz** [chanzuckerberg/sorbet-rails#217]
**Describe the bug:**

Method signatures for models in many cases use `Model::ActiveRecord_Relation`.
However, that is a private constant (https://github.com/rails/rails/issues/30943)

**Steps to reproduce:**

Generate any model types

1. ```rake "rails_rbi:models[Document]```
2. This creates rbi file with multiple method signatures that look like 

```
  sig { params(args: T.untyped).returns(Document::ActiveRecord_Relation) }
  def self.sorted_by(*args); end
```

**Expected behavior:**

Not entirely sure. 

What's interesting is that when I try to access the constant in development but not in non-dev environments.

```
irb(main):002:0> Rails.env
=> "development"
irb(main):003:0> Document::ActiveRecord_Relation
=> Document::ActiveRecord_Relation
```

```
irb(main):024:0> Rails.env
=> "qa"
irb(main):025:0> Document::ActiveRecord_Relation
Traceback (most recent call last):
        1: from (irb):25
NameError (private constant #<Class:0x0000559833e401d0>::ActiveRecord_Relation referenced)
```

**Versions:**
- Ruby: 2.6.0p0
- Rails: 5.2.3
- Sorbet: 0.4.4782
- Sorbet-Rails: 0.5.8.1

**Comment by ilyakatz** [comment]
sorry, seems to be a dup https://github.com/chanzuckerberg/sorbet-rails/issues/211

**Comment by manhhung741** [comment]
@ilyakatz We have a logic to make them dynamic to use in sorbet signature and stuff! Check out https://github.com/chanzuckerberg/sorbet-rails/issues/211

We're trying to improve the documentation for it in #214
