### ISSUE TITLE
Generate perform_now and perform_later

### ISSUE THREAD

**Issue by jaredbeck** [chanzuckerberg/sorbet-rails#239]
**Describe the ~~bug~~ feature:**

In #238 Harry suggested that we should generate RBI for `perform_now` and `perform_later`.

> For sorbet-rails, I think we can generate perform_later and perform_now class methods based on the manually written signature, much like how we generate delivery method for mailers. If you're interested in doing that, I can give you more direction on how to do it. It should be simple because sorbet-rails already has a library method that extracts sorbet signature from a method

**Steps to reproduce:**

1. `rails g job myjob`
2. set job sigil to `false` or higher
3. `rake rails_rbi:all`
4. `ack perform_now sorbet/rails-rbi` no occurrences

**Expected behavior:**

`rake rails_rbi:all` should generate RBI for `perform_now` and `perform_later`.

**Versions:**

- Ruby: all supported
- Rails: all supported
- Sorbet: all supported
- Sorbet-Rails: future :grin:

**Comment by jaredbeck** [comment]
> If you're interested in doing that, I can give you more direction on how to do it.

I'll start by looking at how it's done with mailers, but any tips you have are much appreciated.

**Comment by jaredbeck** [comment]
I just searched the issues to see if `sorbet-rails` supported jobs, and came across this. 🤦‍♂ Hopefully I'll have some time in March to look into this.

**Comment by manhhung741** [comment]
^ I decided to put together a PR to support "rails_rbi:jobs" generation task. Now that we can handle keyword args in our "method signature detection", it's worth adding this task
