### ISSUE TITLE
Segmentation fault on 0.4.4295

### ISSUE THREAD

**Issue by moskvin** [chanzuckerberg/sorbet-rails#24]
```
cat Gemfile
...
group :development do
  gem 'sorbet'
  gem 'sorbet-runtime'
  gem 'sorbet-rails'
end
...
```

```
bundle install
bundle exec srb rbi sorbet-typed
rake rails_rbi:routes
rake rails_rbi:models
```

but when I tried 

```
bundle exec srb tc --suggest-typed --typed=strict --error-white-list=7022 --autocorrect
```

I got following error
```
vendor/bundler/ruby/2.6.0/gems/sorbet-0.4.4295/bin/srb: line 43: 83774 Segmentation fault: 11  "${sorbet[0]}" "${args[@]}"
```
Can you help me to figure out it?

OS: macOS Mojave 10.14.5 (18F132)

**Comment by manhhung741** [comment]
It looks like the segfault is happening on `srb` itself. I think this will be a good question on StackOverflow, but I'll try to help you debug it: 

1. Did you run `srb init` successfully?
2. Does `bundle exec srb tc` work before you run the `rails_rbi` rake tasks?
3. Does `bundle exec srb tc` work after you run each of the rake task?

On #sorbet-ruby slack channel, there have been a few reports of srb crashing or not working properly with gems. I think this maybe a similar situation.

**Comment by moskvin** [comment]
Thank you @manhhung741. Seems all your questions give me answer that the problem in the `srb` gem, I will create new ticket to the project instead.

**Comment by manhhung741** [comment]
You are welcome @moskvin!
