### ISSUE TITLE
Support Rails version 6.0.0rc, 5.1, etc.

### ISSUE THREAD

**Issue by willisplummer** [chanzuckerberg/sorbet-rails#25]
Some preliminary discussion around this problem can be found in this [slack thread](https://sorbet-ruby.slack.com/archives/CJL5B3CEN/p1561148847039400)

when i run `rake rails_rbi:models` it skips all of the instance methods for attributes defined in the schema

e.g.

```
-- Generate sigs for ServiceProviderUsersServiceClientUser --
Skip method 'created_at' because it is not autogenerated by Rails.
Skip method 'created_at=' because it is not autogenerated by Rails.
Skip method 'hourly_rate_in_cents' because it is not autogenerated by Rails.
Skip method 'hourly_rate_in_cents=' because it is not autogenerated by Rails.
```

but in a console:

```
irb(main):005:0> ServiceProviderUsersServiceClientUser.instance_method(:hourly_rate_in_cents).source_location
=> ["/bundle/gems/activerecord-5.1.7/lib/active_record/attribute_methods/read.rb", 34]

irb(main):004:0> ServiceProviderUsersServiceClientUser.instance_method(:hourly_rate_in_cents).owner   
=> #<#<Class:0x0000563fdf89fd58>:0x0000563fdf89fda8>
```

## Deps

- ruby 2.6.2
- rails-5.1.7
- activerecord-5.1.7
- sorbet-0.4.4253
- sorbet-runtime-0.4.4253
- sorbet-rails-0.1.3

**Comment by jasnow** [comment]
I see this too.

**Comment by willisplummer** [comment]
@jasnow can you post your versions of ruby, rails, and activerecord?

**Comment by jasnow** [comment]
> @jasnow can you post your versions of ruby, rails, and activerecord?

Rails and activerecord are both 6.0.0.rc1
Ruby 2.6.3.

**Comment by jasnow** [comment]
Will try same repo with Ruby 2.5.5.

**Comment by jasnow** [comment]
Still getting the "Skip method" messages:
```
-- Generate sigs for Micropost --
Skip method 'content' because it is not autogenerated by Rails.
Skip method 'content=' because it is not autogenerated by Rails.
Skip method 'created_at' because it is not autogenerated by Rails.
Skip method 'created_at=' because it is not autogenerated by Rails.
Skip method 'updated_at' because it is not autogenerated by Rails.
Skip method 'updated_at=' because it is not autogenerated by Rails.
Skip method 'user_id' because it is not autogenerated by Rails.
Skip method 'user_id=' because it is not autogenerated by Rails.
-- Generate sigs for User --
Skip method 'created_at' because it is not autogenerated by Rails.
Skip method 'created_at=' because it is not autogenerated by Rails.
Skip method 'email' because it is not autogenerated by Rails.
Skip method 'email=' because it is not autogenerated by Rails.
Skip method 'name' because it is not autogenerated by Rails.
Skip method 'name=' because it is not autogenerated by Rails.
Skip method 'updated_at' because it is not autogenerated by Rails.
Skip method 'updated_at=' because it is not autogenerated by Rails.
```

**Comment by manhhung741** [comment]
It's likely because of different Rails/ActiveRecord version has different class hierarchy.

**Comment by jasnow** [comment]
What versions of Rails are currently covered?

**Comment by jasnow** [comment]
Found answer: 5.2.3

**Comment by manhhung741** [comment]
Yep, Rails 5.2. I've had a plan to change the way we structure rbis to workaround overridden methods. Will implement it soon. 

If you just want to have it working, you can:
1/ clone `sorbet-rails` locally
2/ point to it from the Gemfile
`gem 'sorbet-rails', path: "~/sorbet-rails"`
and
3/ override
`is_method_autogenerated?` in `model_rbi_formatter#295`

**Comment by manhhung741** [comment]
FYI I pushed code changes to
1/ refactor & remove the method overridden checks
2/ added tests for Rails 5.1.7
I haven't tested with Rails 6.0.0rc but I think it should work.

@jasnow if you find something broken with 6.0.0rc please let me know. I've also set up structure to test multiple Rails app. If you're interested in making it work for 6.0.0rc I'd love to support too.

**Comment by manhhung741** [comment]
I'm going to close the issue for now because we've addressed the main problem raised. If there is any issue with 6.0.0rc please feel free to file a new one.

**Comment by willisplummer** [comment]
@manhhung741 do you plan to release a new version of the gem today?

**Comment by manhhung741** [comment]
Yes! I'm drafting the release note!

**Comment by manhhung741** [comment]
@willisplummer I deployed v0.2.0 to RubyGems! Thanks for reporting the original issue.

**Comment by willisplummer** [comment]
Confirmed that the new version resolves the issue. Thanks for fixing!
