### ISSUE TITLE
README implies any sorbet-rails before 0.6 supports Rails 4.2

### ISSUE THREAD

**Issue by bubaflub** [chanzuckerberg/sorbet-rails#257]
**Describe the bug:**

When I first read

> sorbet-rails supports Rails 4.2 or later.

and

> Notice: From v0.6, we'll stop supporting Rails 4.2. Fixes targeting Rails 4.2 specifically can be merged to v0.5.x branch.

I understood that to mean that any sorbet-rails < 0.6 would support Rails 4.2.  I added sorbet-rails 0.5.9.1 to a Rails 4.2 project and started getting exceptions when trying to generate models.

In 65ac98d5f03ee5c96534d6a74c967bd63381f9d8 it looks like all Rails 4.2 code was removed.

**Steps to reproduce:**

Start a Rails 4.2 project.  Add sorbet.  Add sorbet-rails.  Try to run `rake rails_rbi:all`.  Get exceptions and no generated files.

**Expected behavior:**

To work on Rails 4.2.  I think the README should be updated to indicate that the project no longer supports Rails 4.2 and that the last version was that did.  Looks like 0.5.6 to me.

**Versions:**
- Ruby: ruby 2.4.9p362
- Rails: 4.2.11.1
- Sorbet: 0.5.5281
- Sorbet-Rails: 0.5.9.1

**Comment by manhhung741** [comment]
Thanks for flagging. I'll update the Readme!
