### ISSUE TITLE
Initialize sorbet in rails project causes an error

### ISSUE THREAD

**Issue by rafaelcgs10** [chanzuckerberg/sorbet-rails#264]
**Describe the bug:**
The first step of the **[Initial Setup](https://github.com/chanzuckerberg/sorbet-rails#initial-setup)** requires to run the basic sorbet initialization. But following it doesn't conclude well.

**Steps to reproduce:**

1. run:` rails new app`

2. add to the Gemfile:

```
gem 'sorbet', :group => :development
gem 'sorbet-runtime'
```
3. run: `bundle install`

4. Do the **[Verify installation](https://sorbet.org/docs/adopting#verify-initialization)**
~ No problems until here.

5. run: `srb init`
This step gives an error:
```
/usr/lib/ruby/gems/2.7.0/gems/sorbet-0.5.5316/lib/hidden-definition-finder.rb:149:in `write_constants': /tmp/d20200131-18296-1s6k0uv/reflection.rbi had unexpected errors.
```
More data:
[Full output](https://gist.github.com/rafaelcgs10/4c8c71edf546e48e299be985a6c82dce)
[reflection.json.err](https://gist.github.com/rafaelcgs10/3eb78ae8d1e81c6c68b08bb764b2a698)

**Expected behavior:**
The last step should complete and initialize the folder sorbet/, but it stops with an error.

**Versions:**

- Ruby: ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux]
- Rails: Rails 6.0.2.1
- Sorbet: Sorbet typechecker 0.5.5316 git 84b84770d0646e3e313f83d2785e547c41e6cefd-dirty built on 2020-01-31 06:27:04 GMT debug_symbols=true

**Comment by manhhung741** [comment]
I think this is a problem with sorbet initialization. Do you use rvm? There
is an issue with rvm gems. You can check it out to see if it’s relevant,
otherwise you should also file an issue on sorbet repro.

https://github.com/sorbet/sorbet/issues/2558

Let me know if that’s helpful!

**Comment by rafaelcgs10** [comment]
Hi @manhhung741 , I'm not using rvm. I'm using ruby from Arch Linux repo.

I think I'll create an issue in the sorbet repo.

Thank you!
