### ISSUE TITLE
Mailers rake task fails due to uninitialized constant: ActionMailer

### ISSUE THREAD

**Issue by ric2b** [chanzuckerberg/sorbet-rails#269]
**Describe the bug:**
When I run `bundle exec rake rails_rbi:mailers --trace` the task fails with the following error:
```
NameError: uninitialized constant ActionMailer
/Users/ricardoamendoeira/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/sorbet-rails-0.5.9.1/lib/sorbet-rails/tasks/rails_rbi.rake:96:in `block (2 levels) in <top (required)>'
```

For reference, this is the line that is failing: https://github.com/chanzuckerberg/sorbet-rails/blob/v0.5.9.1/lib/sorbet-rails/tasks/rails_rbi.rake#L96

**Steps to reproduce:**
I just need to run `bundle exec rake rails_rbi:mailers`, the other rake tasks all work fine except for the mailers one.

**Expected behavior:**
The rake task should finish without errors.

**Versions:**

- Ruby: 2.6.1
- Rails: 5.0.7.2
- Sorbet: 0.5.5316
- Sorbet-Rails: 0.5.9.1

**Comment by manhhung741** [comment]
I haven't seen this issue or able to reproduce it. Can you check if ActionMailer is loadable in your repo? You can test by going to `rails c` and type `ActionMailer`.

**Comment by ric2b** [comment]
You're right, it is not, looks like a problem in my project.
Thanks :)

**Comment by oleg-vinted** [comment]
Sorry for commenting on an old bug, but I've just ran into this problem. The cause was that `require "action_mailer/railtie"` wasn't present in `config/application.rb`.

However, the Rails app doesn't use `ActionMailer` and works fine without it, so maybe `rails_rbi:mailers` should emit a warning when `ActionMailer` constant is missing, but otherwise succeed?

**Comment by manhhung741** [comment]
@oleg-vinted Just double-checking, if an app doesn't use "ActionMailer", they don't need to run `rails_rbi:mailers` right? I think the mailer rbi geneneration assumes that it's used with subclass of ActionMailer, and may not work correctly with other kinds of mailers.

**Comment by oleg-vinted** [comment]
@manhhung741 Fair point. So the solution is then not to run `bundle exec rake rails_rbi:all` but run all the rake tasks that are applicable to your case separately, e.g. `bundle exec rake rails_rbi:routes rails_rbi:models rails_rbi:helpers ...`
