### ISSUE TITLE
find_or_create_by! shouldn't require a block parameter

### ISSUE THREAD

**Issue by connorshea** [chanzuckerberg/sorbet-rails#271]
I use find_or_create_by in a few places in my app, and the new signature for it causes type errors that are incorrect.

```
db/seeds/admin.rb:39: find_or_create_by! requires a block parameter, but no block was passed https://srb.help/7021
    39 |  GamePurchase.find_or_create_by!(
    40 |    game: game,
    41 |    user: admin,
    42 |    rating: rand(0..100),
    43 |    completion_status: rand(0..5),
       |...
    46 |    comments: Faker::Lorem.sentence,
    47 |    hours_played: rand(0..100),
    48 |    platforms: platforms,
    49 |    stores: stores
    50 |  )
    sorbet/rails-rbi/active_record_base.rbi:37: defined here
    37 |  def self.find_or_create_by!(attributes, &block); end
```

The block parameter for find_or_create_by! should be nilable. https://github.com/chanzuckerberg/sorbet-rails/blob/f8dbc6b03030d016160c4156f719f60d4f340f62/lib/bundled_rbi/active_record_base.rbi#L24

**Versions:**
- Ruby: 2.6.5 
- Rails: 6.0.0.1
- Sorbet: 0.5.5365
- Sorbet-Rails: git master

**Comment by manhhung741** [comment]
Thanks for flagging. Feel free to send a PR to fix it. Otherwise I’ll try
to do it before eow
