### ISSUE TITLE
HABTM relationships not handled correctly

### ISSUE THREAD

**Issue by modosc** [chanzuckerberg/sorbet-rails#299]
first i wanted to say thanks for this gem and specifically this typechecking between AR and the DB via reflection. it's awesome and it helped us catch a bunch of potential issues recently. 

**Steps to reproduce:**

given a model with a HABTM relationship where the column is `NOT NULL` in the db, we see this output:
```
Note: belongs_to association company is specified as not-null at the DB level but **optional** at the application level. Add a constraint at the app level (using `optional: false`) as a validation hint to Rails.
```

**Expected behavior:**

as far as i can tell there's no way to do this for HABTM, so the messaging should be changed but i'm not sure to what? happy to open a pr to help with this. 

**Versions:**
- Ruby: ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-darwin19]
- Rails: Rails 5.2.4.1
- Sorbet: Sorbet typechecker 0.5.5469 git 42d26158c0a6ae45eb5a0e8eb71c53616190ae2e debug_symbols=true clean=1
- Sorbet-Rails: 0.6.1

**Comment by manhhung741** [comment]
@modosc Oh maybe we didn't filter out HABTM connections and they are treated as "belongs_to" connection.
If you'd like to fix this issue, here is the relevant function. Checkout our Contribution guide for testing changes in the repo:

https://github.com/chanzuckerberg/sorbet-rails/blob/403c283ba4b11025b10fa8217c3aafbfdcc5991f/lib/sorbet-rails/model_plugins/active_record_assoc.rb#L71

**Comment by modosc** [comment]
turns out rails intentionally sets optional: true on both sides of the auto generated habtm classes and there’s no way to change that.

so i think what this is detecting (non nullable id field in a habtm table) is a valid warning, and the suggestion should be to move to a 
 belongs_to:..through: relationship for both sides and to create a rails model for the join table. i’ll take a shot at a pr tomorrow.

**Comment by modosc** [comment]
@manhhung741 would you expect rbi files to be generated for the virtual habtm classes? i've got them generating correctly now (ie, under `model_name/habtm_foo.rbi`) rather than at the top level (where they can potentially overwrite each other) but this requires hacking `expect_files` a bit and i'm not sure i want to go down that road if it's not necessary.

**Comment by manhhung741** [comment]
Can you explain that with an example? What is a virtual habtm class?

**Comment by modosc** [comment]
sure - consider:

```
class Foo < ApplicationRecord
  has_and_belongs_to_many :bars
end

class Bar < ApplicationRecord
  has_and_belongs_to_many :foos
end
```

master currently would generate the following rbi files:
`foo.rbi`
`bar.rbi`
`habtm_foo.rbi`
`habtm_bar.rbi`

the problem is - the `habtm` classes are generated at runtime and are really `Foo::HABTM_Bar` / `Bar::HABTN_Foo` so it seems like these files should be nested. otherwise those files can be overwritten if we have another model like:
```
class Baz < ApplicationRecord
  has_and_belongs_to_many :bars
end
```
because that would also generate another `habtm_bar.rbi` file. 

in my branch these classes would generate:
`foo.rbi`
`foo/habtm_bar.rbi`
`bar.rbi`
`bar/habtm_foo.rbi`
`baz.rbi`
`baz/habtm_bar.rbi`

etc.

**Comment by manhhung741** [comment]
I see. It makes sense to nest habtm classes in its nested scope! Please feel free to send a PR to fix that.  
> this requires hacking expect_files a bit and i'm not sure i want to go down that road if it's not necessary

If we could merge `foo.rbi` and `foo/habtm_bar.rbi` then it will not require changing `expected_files` but if it's difficult, I think changing `expected_files` helper method is fine to me :-)

**Comment by modosc** [comment]
thanks @manhhung741 , when do you think another release will go out?

**Comment by manhhung741** [comment]
Thank you! I'll try to do a release next week. This week I'm a bit occupied.
