### ISSUE TITLE
Problem with spec/support/5.2.3/db/migrate symbolic link

### ISSUE THREAD

**Issue by jasnow** [chanzuckerberg/sorbet-rails#33]
FYI:

When I "git pull upstream" this morning to resync your code with my fork, I got:
```
Broken symlinks detected:
/Users/USER/Projects/sorbet-rails/spec/support/5.2.3/db/migrate

✗ One or more pre-commit hooks failed
```
Tried all kinds of things but the only thing that worked was to delete it from my copy.
Then "git commit" and "git push" worked.
Then I tried to add it back and got the same error as above.

**Comment by manhhung741** [comment]
Thanks. I'll take a look!

**Comment by manhhung741** [comment]
https://github.com/chanzuckerberg/sorbet-rails/pull/34
We probably should set up some git hook to prevent this from happening. Thank you!

**Comment by jasnow** [comment]
Verified fix.
