### ISSUE TITLE
GeneratedUrlHelpers does not implement ActiveSupport::Concern so url helpers don't work

### ISSUE THREAD

**Issue by dtropp** [chanzuckerberg/sorbet-rails#335]
**Describe the bug:**
The provided GeneratedUrlHelpers module which wraps the Rails `Rails.application.routes.url_helpers` module stops the module binding to the class correctly.

Gives this error:
```
Started GET "/guidelines/4"
Processing by Guidelines::GuidelinesController#show as HTML
  Parameters: {"id"=>"4"}
NameError (undefined local variable or method `default_url_options' for #<Guidelines::GuidelinePresenter:0x00007f8ec04c7880>
Did you mean?  default_url_options=
               @@default_url_options)

NameError - undefined local variable or method `default_url_options' for #<Guidelines::GuidelinePresenter:0x00007f8ec04c7880>
Did you mean?  default_url_options=
               @@default_url_options:
  app/concepts/guidelines/guideline_presenter.rb:42:in `block in topics_raw'
  app/concepts/guidelines/guideline_presenter.rb:36:in `topics_raw'
  app/concepts/guidelines/guideline_presenter.rb:26:in `raw'
  app/concepts/guidelines/guideline_presenter.rb:16:in `to_json'
  app/concepts/guidelines/guidelines_controller.rb:11:in `show'
```
**Steps to reproduce:**
```
class GuidelinePresenter
    extend T::Sig
    include GeneratedUrlHelpers

   def my_url
     new_guideline_path()
   end
end
```

**Expected behavior:**
Generates the path using the rails url helper, without needing to implement `default_url_options()`.

Workaround:
```
# typed: false

  class GuidelinePresenter
    extend T::Sig
    UrlHelpers = Rails.application.routes.url_helpers
    include UrlHelpers

    def my_url
      new_guideline_path()
    end
  end
```

**Versions:**

- Ruby: ruby 2.6.6p146 (2020-03-31 revision 67876) [x86_64-darwin18]
- Rails: Rails 5.2.4.3
- Sorbet: Sorbet typechecker 0.5.5666 git f994f9d74e5ae379c76714a9b13872ece96ec3a1 debug_symbols=true clean=1
- Sorbet-Rails: sorbet-rails (0.6.5.1)

**Comment by manhhung741** [comment]
Oh interesting. Let me double-check where `default_url_options` is coming from.

**Comment by manhhung741** [comment]
Turns out this work for the "_path" method but not the "_url" method.
```
> Rails.application.routes.url_helpers.test_index_url
ArgumentError (Missing host to link to! Please provide the :host parameter, set default_url_options[:host], or set :only_path to true)
```
But I can fix it so that the `_path` method work without defining `default_url_options`

**Comment by dtropp** [comment]
We are only using the _path methods so that would be very helpful. Thanks!
