### ISSUE TITLE
`pluck_to_tstruct` with associations proposal

### ISSUE THREAD

**Issue by DanielGilchrist** [chanzuckerberg/sorbet-rails#336]
Hello!

When using `pluck` you can join on another table and pluck their columns as well like so:
```ruby
Team.joins(:team_group).pluck(:id, :name, "team_groups.id", "team_groups.name")
```

Currently with `pluck_to_tstruct` this isn't possible and you'd have to use `pluck` and create the `T::Struct` objects yourself. I was thinking of making a PR to allow this by mapping association keys as you would use them with `pluck` to a `T::Struct`s props. In terms of the API I was thinking of something along the lines of this:
```ruby
class TTeamStruct < T::Struct
  const :id, Integer
  const :name, String
  const :team_group_id, Integer
  const :team_group_name, String
end

Team.joins(:team_group).pluck_to_tstruct(TA[TTeamStruct].new, associations: {
  "team_groups.id": :team_group_id,
  "team_groups.name": :team_group_name
})
```

Just wanted to make an issue first to get some opinions on whether people are keen and what people would think is a good/intuitive API

Cheers!

**Comment by manhhung741** [comment]
Hi @DanielGilchrist ! The suggested API makes sense to me. I probably would revert the mapping in associations though, something like:

```
Team.joins(:team_group).pluck_to_tstruct(TA[TTeamStruct].new, associations: {
  team_group_id: "team_groups.id",
  team_group_name: "team_groups.name",
})
```

**Comment by DanielGilchrist** [comment]
Awesome thanks for the reply! I agree with swapping the associations makes a lot more sense that way. I'll make a PR soon :)
