### ISSUE TITLE
Unable to resolve ActiveRecord::Batches::BatchEnumerator

### ISSUE THREAD

**Issue by dikond** [chanzuckerberg/sorbet-rails#355]
**Describe the bug:**

After upgrade to v0.6.5.1 sorbet fails because of this error:
```
sorbet/rails-rbi/models/story_audience_tos_token.rbi:246: Unable to resolve constant BatchEnumerator https://srb.help/5002
     246 |    ).returns(ActiveRecord::Batches::BatchEnumerator)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
I checked [sorbet-typed](https://github.com/sorbet/sorbet-typed) repo and it does not include signatures for `ActiveRecord::Batches::BatchEnumerator`.

I think it should have been catched by the sorbet-rails test suite? 

I also did not expect 300+ errors on upgrade since it's a patch-level version bump...

**Expected behavior:**

I'd expect sorbet-rails not to reference any types that could not be discovered by `srb rbi init` or `srb rbi update`

**Versions:**

- Ruby: 2.6.5
- Rails: 5.2.3
- Sorbet: 0.5.5569
- Sorbet-Rails: 0.6.5.1

**Comment by frewsxcv** [comment]
Yep, came here to report this too.

**Comment by manhhung741** [comment]
That’s new to me. I think BatchEnumerator is part of Rails and should be
there in gem rbi or hidden-definition rbi.

Is there any other error in the 300 errors you saw?

**Comment by manhhung741** [comment]
We use tapioca and it's in our `sorbet/rbi/gems/activerecord@6.0.2.rbi` file
```
class ActiveRecord::Batches::BatchEnumerator
```

In sorbet's generated gem rbi, I also found it it `sorbet/rbi/gems/activerecord.rbi` (for Rails 5.2)
```
class ActiveRecord::Batches::BatchEnumerator
  def delete_all(*args, &block); end
  def destroy_all(*args, &block); end
  def each; end
  def each_record; end
  def initialize(relation:, of: nil, start: nil, finish: nil); end
  def update_all(*args, &block); end
  include Enumerable
end
```

Can you double-check if it is there in your activerecord.rbi? And what if you run `bundle exec srb rbi gems` is it added?

It could be also a regression introduced by sorbet recently. Let me check that.

**Comment by manhhung741** [comment]
I checked with the latest version of sorbet, it still works and BatchEnumerator is in rbi/gems/activerecord.rbi. If you find no reference to BatchEnumerator, please try to run either command below and it should resolve the issue
to regenerate gem rbi:
```
bundle exec srb rbi gems
```
or to put the const in todo.rbi
```
bundle exec srb rbi todo
```

**Comment by dikond** [comment]
Hey @manhhung741 thanks for looking into it. 

> Is there any other error in the 300 errors you saw?

Yes there were other errors. But I always get errors when updating sorbet + sorbet-rails. I didn't went over each and every one but the wast majority was caused by the error I showed above.

> Can you double-check if it is there in your activerecord.rbi? 

Recursive search for `ActiveRecord::Batches::BatchEnumerator` does not show any results. But I do see `rbi` definitions for an `ActiveRecord::Batches` under `hidden.rbi`. 

> And what if you run bundle exec srb rbi gems is it added?

I ran `bundle exec srb rbi update` and it added `ActiveRecord::Batches::BatchEnumerator` in `/sorbet/rbi/todo.rbi`. After that I do not see the error I showed in the issue, but almost all my files are `typed: ignored` now.

**Comment by dikond** [comment]
So I'm not sure how to handle this "bug" to be honest. This exact case for missing `BatchEnumerator` can be fixed by pushing signatures to the `sorbet-typed` repo. I guess I just was surprised that `sorbet-rails` added signatures that are missing under our `/sorbet/rbi/`directory.

I think what can help is to mention what you recommended in your previous post. Or try to push signatures to sorbet-typed before referencing such constants in `sorbet-rails`.

**Comment by manhhung741** [comment]
It’s still a mystery to me why you don’t have it in your rbi file. Given
that this is a standard class in Rails, I didn’t expect using it to be
causing issue. Usually sorbet itself would generate RBI for those
correctly, and I find those in my generated rbi as well.

https://api.rubyonrails.org/classes/ActiveRecord/Batches/BatchEnumerator.html

**Comment by frewsxcv** [comment]
https://github.com/sorbet/sorbet-typed/pull/266

**Comment by dikond** [comment]
I don't know how sorbet generates rbi for the gems, but I had to push signatures for several modules and pretty basic stuff like `self.ignored_columns` or `self.table_name` to sorbet-typed. I wouldn't rely on the fact that if that's a rails class then it _should_ be in the project rbi.
