### ISSUE TITLE
Rails has_many, belongs_to, validates, etc. are not defined

### ISSUE THREAD

**Issue by claudeomusic** [chanzuckerberg/sorbet-rails#364]
**Describe the bug:**
Maybe I'm misunderstanding what's supposed to happen, but I was under the impression that running `bundle exec rake rails_rbi:models` would generate type data for standard rails things like `has_many`, `belongs_to`, `validates`, and so forth. I can see that the associations themselves were generated, e.g.
```
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
end
```

generated the corresponding sigil:

```
  sig { returns(::User::ActiveRecord_Associations_CollectionProxy) }
  def users; end
```

Resulting `srb tc` output:
```
Method has_and_belongs_to_many does not exist on T.class_of(Role) https://srb.help/7003
     3 |  has_and_belongs_to_many :users, :join_table => :users_roles
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
Will we need to manually add type information for the rails methods themselves?

**Steps to reproduce:**
Uncertain

**Expected behavior:**
Auto-genereated type data in rbis

**Versions:**
- Ruby: 2.6.6
- Rails: 5.2.4.2
- Sorbet: 0.5.5823
- Sorbet-Rails: 0.7.1

**Comment by DenDos** [comment]
@claudeomusic I'm having the same issue. See you've closed the issue, how did you solve this?
