### ISSUE TITLE
Request clarification of syntax for model RBI regeneration

### ISSUE THREAD

**Issue by peternixey** [chanzuckerberg/sorbet-rails#366]
**Describe the bug:**

When creating RBI files for a new Rails model, the instructions in the readme specify:

`bundle exec rake rails_rbi:models[ModelName,AnotherOne,...]`

However running the command:

`bundle exec rake rails_rbi:models [Session, AuthAttempt]`

generates *all* of the models' RBI files and ends with the statement:

`Don't know how to build task '[Session,' (See the list of available tasks with 'rake --tasks')`

**Steps to reproduce:**

Run the command:

`bundle exec rake rails_rbi:models [User]` (assuming you have a User model

**Expected behavior:**

The command works - I've obviously got the syntax incorrect but the docs seem ambiguous (or else I just don't understand them 🤠)

**Versions:**

- Ruby:
- Rails:
- Sorbet:
- Sorbet-Rails:

**Comment by manhhung741** [comment]
Thanks for reaching out, Peter! Rake command doesn’t accept space. Your
command would work when removing the space character after the comma.

bundle exec rake rails_rbi:models [Session,AuthAttempt]

**Comment by peternixey** [comment]
Thanks for coming back to me Harry. Unfortunately even without the space it still fails. I copied and pasted your command and got:

````
bundle exec rake rails_rbi:models [Session,AuthAttempt]

...

-- Generate sigs for ActiveRecord::InternalMetadata --
-- Generate sigs for ActiveRecord::SchemaMigration --
rake aborted!
Don't know how to build task '[Session,AuthAttempt]' (See the list of available tasks with `rake --tasks`)
````

There's obviously something simple I'm missing... 🧐

**Comment by manhhung741** [comment]
Oh you have extra space between models and []. It should be a continuous string without space

```
rake rails_rbi:models[User,AuthAttempt]
```

**Comment by peternixey** [comment]
that worked - thank you!


Founder of Copyin
 <https://www.linkedin.com/in/peternixey>LinkedIn <https://www.linkedin.com/in/peternixey>
Twitter <https://twitter.com/peternixey>

 <https://copyin.com/?utm_source=footer>
 <https://copyin.com/?utm_source=footer>
