### ISSUE TITLE
Rescue_from in ApplicationController is not detected

### ISSUE THREAD

**Issue by jcoyne** [chanzuckerberg/sorbet-rails#379]
**Describe the bug:**
```
srb tc
app/controllers/application_controller.rb:13: Method rescue_from does not exist on T.class_of(ApplicationController) https://srb.help/7003
    13 |  rescue_from ActionPolicy::Unauthorized, with: :deny_access
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Steps to reproduce:**
Create a class like this and run `srb tc`
```ruby
# typed: true
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  extend T::Sig
  rescue_from ActionPolicy::Unauthorized, with: :deny_access
  # ...
end
```

**Expected behavior:**
It should recognize that ActiveSupport::Rescuable is included: https://github.com/rails/rails/blob/b2eb1d1c55a59fee1e6c4cba7030d8ceb524267c/activesupport/lib/active_support/rescuable.rb

**Versions:**

- Ruby: ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-darwin19]
- Rails: 6.0.3.4
- Sorbet: Sorbet typechecker 0.5.5981 git ae42e259185888423552d630cdd48acd86b2e295 debug_symbols=true clean=1
- Sorbet-Rails: 0.7.1

**Comment by manhhung741** [comment]
That's interesting. We use "rescue_from" in our code as well and don't run into this issue. Can you check if there is any error in sorbet initialization? for example, check for "typed: ignore" file. They usually are the culprit of missing library methods

**Comment by DenDos** [comment]
@jcoyne just wondering if there any update on this? Were you able to fix it somehow?

**Comment by jcoyne** [comment]
I don't seem to hit it anymore, but I've upgraded to Rails 6.1.2.1 since this was reported. Perhaps that fixed it :shrug
