### ISSUE TITLE
ActiveJob: Method queue_as does not exist

### ISSUE THREAD

**Issue by bmulholland** [chanzuckerberg/sorbet-rails#382]
**Describe the bug:**
When using ActiveJob, we set the queue to use with `queue_as`: https://edgeguides.rubyonrails.org/active_job_basics.html. However, this method doesn't exist in the current definitions, so an error is generated.

**Steps to reproduce:**
```
# typed: true

class TestJob < ActiveJob::Base
  queue_as :default
end
```

**Expected behavior:**
Sorbet knows about `queue_as` and accepts it as a valid call.

**Versions:**

- Ruby: 2.7.2p137
- Rails: 6.0.3.4
- Sorbet: 0.5.6134
- Sorbet-Rails: 0.7.1

**Comment by bmulholland** [comment]
Is this fix as simple as adding queue_as inside ActiveJob::Base? https://github.com/chanzuckerberg/sorbet-rails/blob/4510de9cd0c897f343c832bca2b384ec6dff96b2/sorbet/rbi/gems/activejob.rbi#L170

**Comment by manhhung741** [comment]
@bmulholland That's right, there should be a sig for `queue_as` method in ActiveJob::Base. But usually this method is not generated by sorbet-rails; it should be generated by sorbet itself when you initialize your project (or tapioca if you use it). Do you have a generated `sorbet/gems/activejob.rbi` file?

**Comment by bmulholland** [comment]
Oh, weird. Yeah, I have a `sorbet/rbi/gems/activejob.rbi`, and that has a `class ActiveJob::Base` which includes `extend ActiveJob::QueueName::ClassMethods` which does indeed define `def queue_as(part_name = nil, &block); end`. So it _seems_ that queue_as should be defined. That's super weird.

Sounds like that means it's not an issue for `sorbet-rails`, but would you have any tips on how to debug this sort of thing? Is there a way to list what methods Sorbet thinks a class has? Can't find anything in five minutes of Google + searching Sorbet docs.

**Comment by manhhung741** [comment]
Sure! I'd like to help debugging! Can you paste the error message that sorbet show, and the original code?
Also, can you check if there is any `# typed: ignore` file? Does `activejob.rbi` has typed: true sigil on top of it?

**Comment by bmulholland** [comment]
Hey, really appreciate it.

I'm repro-ing with the example in my original post, which is `typed: true`, but `activejob.rbi` is indeed `typed: **ignore**`. Sounds like that's the issue? But this file is auto-generated - do you know why it would be set to ignore?

The error I get is:
```
app/jobs/test_job.rb:4: Method queue_as does not exist on T.class_of(TestJob) https://srb.help/7003
     4 |  queue_as :default
          ^^^^^^^^^^^^^^^^^
  Did you mean:
    sorbet/rbi/hidden-definitions/hidden.rbi:8039: ActiveJob::Base.queue_name
    8039 |  def self.queue_name(); end
            ^^^^^^^^^^^^^^^^^^^^^
```

**Comment by manhhung741** [comment]
I think it is due to sorbet bug with `srb rbi suggest-typed` which sorbet runs at the end of the process. I'm not sure why this happened.  IIRC the script is buggy and changes sigil incorrectly. You should file an issue on the [sorbet](https://github.com/sorbet/sorbet) repo. 

You should be able to change the `typed: ignore` files, especially all files in the `sorbet/` folder. If sorbet flags any type errors after that, then try to resolve them. Generally rule of thumb is to not have `typed: ignore` files.

**Comment by bmulholland** [comment]
Thanks @manhhung741. Actually it looks like `typed: ignore` is correct; when I change to `typed: false`, all sorts of errors are thrown about the rbi file itself - see the rbi file and srb output here: https://gist.github.com/bmulholland/b2da0be82c0dc948a01f84c276858dde

Is it possible that something isn't compatible with Rails 6 or Ruby 2.7?

Trying to gather as much information to help with a bug report for sorbet.

**Comment by bmulholland** [comment]
Bingo: https://sorbet.org/docs/faq#what-platforms-does-sorbet-support

e.g. https://github.com/sorbet/sorbet/issues/2994

Closing this out.

**Comment by manhhung741** [comment]
Yeah. @bmulholland maybe you can give [tapioca](https://github.com/Shopify/tapioca) a try. It replaces `sorbet/gems` folder generated by sorbet with a different, compatible generation code. Currently, I'm using it with our Rails 6, Ruby 2.7 app and I think it works.

**Comment by manhhung741** [comment]
Generally, I've found tapioca to be an useful tool to manage gems rbis. When you add or remove gems, it's faster to use tapioca than sorbet to generate the gem RBI.

**Comment by bmulholland** [comment]
Thanks, I was going to ask if you recommend tapioca. I gave it a shot before but ran into some issues that I don't recall; I'll give it another try. Really appreciate your help here - thank you!
