### ISSUE TITLE
Method request does not exist on Api::BaseController

### ISSUE THREAD

**Issue by DenDos** [chanzuckerberg/sorbet-rails#403]
**Describe the bug:**
I'm seeing this error for my controller. Can't find in docs how to solve this issue 
![image](https://user-images.githubusercontent.com/12713564/108511303-2c33e400-72d9-11eb-9d7a-70e44e4d7c4d.png)

**Expected behavior:**
Don't get this error 😛

**Versions:**
- Ruby: ruby 2.7.2p137
- Rails: Rails 6.0.3.5
- Sorbet: (0.5.6287)
- Sorbet-Rails: (0.7.3)

**Comment by DenDos** [comment]
Fixed this by adding a custom rbi definition. But I'm not sure that this is the right way
<img width="1178" alt="Screen Shot 2021-02-19 at 23 06 14" src="https://user-images.githubusercontent.com/12713564/108549773-13422780-7307-11eb-973a-71a39290d8bb.png">

**Comment by manhhung741** [comment]
@DenDos that looks like a reasonable fix! At the same time, this is usually handled by [sorbet-typed](https://github.com/sorbet/sorbet-typed/blob/master/lib/actionpack/all/actionpack.rbi#L821) and it works out of the box for me. Can you check if you have this file: `sorbet/rbi/sorbet-typed/lib/actionpack/all/actionpack.rbi`? If you don't, check `srb rbi sorbet-typed`!
