### ISSUE TITLE
sigs missing blocks raise errors in latest sorbet release (0.5.6341+)

### ISSUE THREAD

**Issue by dpkp** [chanzuckerberg/sorbet-rails#406]
**Describe the bug:**
Recent sorbet releases (0.5.6341+) will raise errors when passing a block to a method with a sig that does not declare a block parameter. In previous releases, passing a block in this context would be silently ignored. See https://github.com/sorbet/sorbet/pull/4061

This change causes sorbet errors for common rails block methods: `any?` `none?` `many?`, `one?`, and `select?` (select? may be a special case due to the issue described here: https://github.com/chanzuckerberg/sorbet-rails#select-with-a-block).

At least with respect to any/none/many/one, I believe the root cause is the current definitions from sorbet-typed do not include blocks: https://github.com/sorbet/sorbet-typed/blob/master/lib/activerecord/all/activerecord.rbi#L2431-L2445 , which are vendored here at https://github.com/chanzuckerberg/sorbet-rails/blob/master/sorbet/rbi/sorbet-typed/lib/activerecord/all/activerecord.rbi#L1435-L1449

Workaround is to add `.to_a` prior to all uses of any?/none?/many?/one?, which avoids the broken activerecord.rbi sigs.

**Steps to reproduce:**
Upgrade to sorbet >= 0.5.6341
Model.any? { |a| true }
bundle exec srb tc

**Expected behavior:**
Should not raise errors when passing a block to any?/none?/many?/one?

**Versions:**

- Ruby: 2.6.2p47
- Rails: 6.0.3.5
- Sorbet: 0.5.6341
- Sorbet-Rails: 0.7.0

**Comment by connorshea** [comment]
Based on my testing I'm pretty sure the fix is just to change those signatures to this?:
```ruby
  sig { params(block: T.proc.params(arg0: Elem).returns(T::Boolean)).returns(T::Boolean) }
  def any?(&block); end

  sig { params(block: T.proc.params(arg0: Elem).returns(T::Boolean)).returns(T::Boolean) }
  def many?(&block); end

  sig { params(block: T.proc.params(arg0: Elem).returns(T::Boolean)).returns(T::Boolean) }
  def none?(&block); end

  sig { params(block: T.proc.params(arg0: Elem).returns(T::Boolean)).returns(T::Boolean) }
  def one?(&block); end
```

**Comment by connorshea** [comment]
This is now fixed in the upstream sorbet-typed signatures, just need to update sorbet-rails to use them.

**Comment by manhhung741** [comment]
Thank you @connorshea for the fix! Sorbet-rails does not bundle sorbet-typed in the API (it's included for internal development only). So anyone can update their sorbet-typed with `srb rbi sorbet-typed` and they would get the new signature!

**Comment by manhhung741** [comment]
Arguably, there are methods affected like `select` that we may want to change in sorbet-rails though. LMK if you run into issue with `select` and we can discuss how we should fix it.

**Comment by danhuynhdev** [comment]
I've ran into the issue with `select` after upgrading `sorbet-rails`. Update the rbi manually like this for now but would love for it to be fixed here.
```ruby
  sig { params(args: T.untyped, block: T.untyped).returns(ReportCategory::ActiveRecord_Relation) }
  def select(*args, &block); end

```
