### ISSUE TITLE
active_record_relation.rbi ends up with false sigil

### ISSUE THREAD

**Issue by connorshea** [chanzuckerberg/sorbet-rails#407]
With the change to sorbet-typed in [this PR](https://github.com/sorbet/sorbet-typed/pull/350), the `sorbet/rails-rbi/active_record_relation.rbi` that gets generated by sorbet-rails is now marked as `typed: false` because it's duplicating the Elem defined in sorbet-typed.

I'm not sure this really has any significant negative effect, since the types defined in both files still get used, but I figured I'd mention it so we could discuss whether we should fix the problem.

**Comment by manhhung741** [comment]
Thanks for flagging. I *think* we can remove the "Elem" definition 🤔

**Comment by manhhung741** [comment]
I've fixed it in #412

**Comment by ColinBohn** [comment]
Hi @manhhung741,

First off, thanks for your work on maintaining this project! I've run into an issue with this change, as I'm generating ActiveRecord RBIs with [tapioca](https://github.com/Shopify/tapioca) and not pulling them from sorbet-typed, so removing this definition causes numerous errors of:
 ```
 type_member type Enumerable::Elem used outside of the class definition
 ```
 
I'll just pin an older gem version for now, but I wanted to bring this to attention. Thanks again!

**Comment by connorshea** [comment]
@ColinBohn as a workaround, I'd probably recommend just adding a `custom.rbi` file in your `sorbet/` directory with contents like this:

```
# typed: true
class ActiveRecord::Relation
  Elem = type_member(fixed: T.untyped)
end
```
