### ISSUE TITLE
Has_many with scope on association

### ISSUE THREAD

**Issue by akefeli** [chanzuckerberg/sorbet-rails#425]
I have a `has_many` association with a scope defined on the associated class. But srb is expecting method `completed` to be defined in Person class.
Is there a workaround for this?

**Steps to reproduce:**
```
class Person
  has_many :jobs, -> { completed }
end

class Job
  scope :completed, -> { where... }
end
```

`Method completed does not exist on T.class_of(Person) https://srb.help/7003`

**Expected behavior:**
It should not complain about method being missing

**Versions:**

- Ruby: 2.7.2
- Rails: 6.0.3.7
- Sorbet: 0.5.6388
- Sorbet-Rails: 0.7.3

**Comment by DanielGilchrist** [comment]
To get around this you can explicitly call the scope from the model class like so:

```ruby
class Person
  has_many :jobs, -> { Job.completed }, class_name: "Job"
end

class Job
  scope :completed, -> { where... }
end
```

**Comment by akefeli** [comment]
Ty! @DanielGilchrist
