### ISSUE TITLE
Decide whether to drop Ruby 2.4 and Ruby 2.5

### ISSUE THREAD

**Issue by connorshea** [chanzuckerberg/sorbet-rails#428]
Sorbet is currently incompatible with Ruby versions before 2.6 due to its usage of endless ranges. That's causing problems with sorbet-rails because its CI is failing now. I'm unsure if the upstream will fix this (see sorbet/sorbet#4265 / sorbet/sorbet#4281) and if they won't, we're going to need to drop support for the older Ruby versions as well.

I also think we should drop Rails 5.0 and 5.1, but that's a separate thing.

**Comment by connorshea** [comment]
Looks like they fixed it in Sorbet. I still think we should consider shedding some of that extra weight, though.

**Comment by manhhung741** [comment]
I think I've dropped 5.0 and 5.1 and some Ruby version. I'll see if we should drop more.
