### ISSUE TITLE
Improve gem tests by running Sorbet on a sample input

### ISSUE THREAD

**Issue by gogiel** [chanzuckerberg/sorbet-rails#59]
Gem's tests compare expected output from templates with the output from the code.
It is very useful as it proves that the rbi files are generated.

However there's no test that proves that generated rbi files are valid.

Task:
test generated `rbi` files against a sample code using `sorbet`

**Comment by manhhung741** [comment]
Totally. I’m going to look into that!

**Comment by manhhung741** [comment]
Added tests for 
- srb init
- srb tc
- srb tc -lsp
