### ISSUE TITLE
Negative enum scope support on Rails 6.0

### ISSUE THREAD

**Issue by connorshea** [chanzuckerberg/sorbet-rails#67]
[Negative enum scopes](https://github.com/rails/rails/pull/35381) are a feature in Rails 6, it'd be nice if they were generated as part of sorbet-rails :)

**Expected behavior:**
sorbet-rails would generate negative enum scopes, e.g. if you had an enum for User, like so:

```ruby
enum role: {
  member: 0,
  moderator: 1,
  admin: 2
}
```

Then you could write code like this:

```ruby
user = User.new
return PermissionsError if user.not_admin?
```

Currently, it doesn't seem that sorbet-rails generates these.

**Comment by manhhung741** [comment]
Thanks for flagging. Seems to be easy to add!

**Comment by connorshea** [comment]
It looks like sorbet-rails already generates these on Rails 6, and actually the `not_admin?` method wouldn't exist. It only generated `not_admin`.

**Comment by manhhung741** [comment]
Yeah. Turns out the enum scopes are defined through named scope. The named
scope plugin takes care of generating those automatically.
