### ISSUE TITLE
Generate a helpers.rbi

### ISSUE THREAD

**Issue by connorshea** [chanzuckerberg/sorbet-rails#87]
Rails helpers are generated with no parent, so Sorbet thinks they don't include `Kernel`, which means something like this will cause the typechecker to fail, despite being perfectly valid:

```ruby
# typed: true
module ApplicationHelper
  def example
    puts "test"
  end
end
```

If a Rails app has helper modules, a `helpers.rbi` should be generated like so:

```ruby
# typed: strong
module ApplicationHelper
  include Kernel
end

module GamesHelper
  include Kernel
end

module SettingsHelper
  include Kernel
end
```

I'm not sure if this is quite the correct fix, but I think it makes sense. It'd also be a base to build from for better helper support in the gem.

**Comment by manhhung741** [comment]
Sounds like a good idea. If you'd like to send a PR to include this to the generation code, please feel free to do so. 

Are there more things you'd like to add to the helpers?

**Comment by connorshea** [comment]
ActionView methods, mostly. I'm still trying to figure out what exactly the included actionview classes/modules are, though.

**Comment by connorshea** [comment]
you can get a list of Helper modules with `ApplicationController.modules_for_helpers([:all])`
```
irb(main):011:0> ApplicationController.modules_for_helpers([:all])
=> [ApplicationHelper, GamesHelper, GenresHelper, HomeHelper, PlatformsHelper, SettingsHelper, DeviseHelper]
```
