### ISSUE TITLE
Fix warning "class variable access from toplevel"

### ISSUE THREAD

**Issue by manhhung741** [chanzuckerberg/sorbet-rails#90]
**Describe the bug:**

We would like to get rid of this warning
```lib/sorbet-rails/tasks/rails_rbi.rake:7: warning: class variable access from toplevel```

**Steps to reproduce:**

It's because I added the following code in rails_rbi.rake. If we find another way to copy file, it'll be fine
```
# this is ugly but it's a way to get the current directory of this script
# maybe someone coming along will know a better way
@@sorbet_rails_rake_dir = File.dirname(__FILE__)
```

**Expected behavior:**
No warning

**Versions:**

- Ruby:
- Rails:
- Sorbet:
- Sorbet-Rails: 0.4.0

**Comment by jasnow** [comment]
Agree
