### ISSUE TITLE
Add rake rails_rbi:all

### ISSUE THREAD

**Issue by connorshea** [chanzuckerberg/sorbet-rails#94]
I'd like to regenerate the RBIs for models, routes, and helpers with one task. `rake rails_rbi:all` (or maybe just `rake rails_rbi`?) should invoke each of the three RBI tasks.

**Comment by manhhung741** [comment]
Sounds good to me. If you want to refresh everything it'll be useful. The models generation task, however, is a slow one that people should still run `rake rails_rbi:models[ModelName]` when there is a small change

**Comment by manhhung741** [comment]
I like rake rails_rbi:all. It’s more explicit
